// Generated by Xata Codegen 0.18.0. Please do not edit.
import {
  BaseClientOptions,
  buildClient,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';

const tables = [
  {
    name: 'jobs',
    columns: [
      { name: 'company', type: 'string' },
      { name: 'title', type: 'string' },
      { name: 'link', type: 'string' },
      { name: 'geography', type: 'string' },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Jobs = InferredTypes['jobs'];
export type JobsRecord = Jobs & XataRecord;

export type DatabaseSchema = {
  jobs: JobsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    'https://Joseph-Maramba-Weyao-s-workspace-6bc164.eu-west-1.xata.sh/db/job-board-db',
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
